### ISSUE TITLE
vagrant-protobox.rb:23:in `system_dir': undefined method `join' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by GabLeRoux** [protobox/protobox#162]
I just installed protobox to give it a try, and I can't get it to run, here's What I get:

```
$ vagrant protobox install 'http://getprotobox.com/share/<snip>'

==> protobox: Downloading config: http://getprotobox.com/share/<snip> => config/name
/Users/gableroux/.vagrant.d/gems/gems/vagrant-protobox-0.0.2/lib/vagrant-protobox.rb:23:in `system_dir': undefined method `join' for nil:NilClass (NoMethodError)
    from /Users/gableroux/.vagrant.d/gems/gems/vagrant-protobox-0.0.2/lib/vagrant-protobox/action/install.rb:98:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
    from /Users/gableroux/.vagrant.d/gems/gems/vagrant-protobox-0.0.2/lib/vagrant-protobox/command/install.rb:57:in `execute'
    from /Users/gableroux/.vagrant.d/gems/gems/vagrant-protobox-0.0.2/lib/vagrant-protobox/command/root.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

I had some troubles trying to install it, but finally maneged to install it with vagrant `1.7.2`. 

```
vagrant plugin install vagrant-protobox

Installing the 'vagrant-protobox' plugin. This can take a few minutes...
Installed the plugin 'vagrant-protobox (0.0.2)'!
Post install message from the 'vagrant-protobox' plugin:

********************************************************************************

  Web GUI: http://getprotobox.com/

  Follow @getprotobox on Twitter for announcements, updates, and news.
  https://twitter.com/getprotobox

********************************************************************************
```

I tried to run `vagrant protobox install` with other generated urls without luck.  
Thanks for your time :)

**Comment by stefangeorg** [comment]
This isn't working with vagrant 1.8.1 in ubuntu 16.04
